### PR TITLE
Add http_proxy support

### PR DESCRIPTION
**Pull request by analogue**
Debugging async http isn't fun, but it helps to have an http proxy as a debugging aid :-)

### CODE REVIEW

**Comment by analogue** [comment]
Seems we have a flaky test :-(

**Comment by dnephin** [comment]
I think most clients will use a different proxy (and environment variable) for http and https?

That's probably fine to add later though.

lgtm

**Comment by prat0318** [comment]
On going through the PR i am curious as to how http proxy becomes helpful for debugging like for setting breakpoints etc?

**Comment by analogue** [comment]
For seeing request/response flow/content without having to resort to breakpoints or executing something in a debugger.

**Pull request merged**
