### PR TITLE
Fix issue where errors from request arent getting raised

### PR DESCRIPTION
**Pull request by bpicolo**
Pretty sure the primary issue was that we were issuing the request inside the reactor which is, I believe, not correct.

Either way, test didnt work before / works after.

### CODE REVIEW

**Comment by analogue** [comment]
@jnb Want to give this a once over?

**Comment by bpicolo** [comment]
I guess I can elucidate on the bug a bit more, which comes out through the unique way in which we mix deferreds, eventuals, and futures >.>.

The issue is that, with all those things running in the reactor thread, the <crochet> deferred (that is, the one generated by crochet for the eventual) was receiving the error, and the crochet deferred has no knowledge whatsoever of the future, so isn't putting a callback anywhere useful on error. The future then proceeds to never return anything

**Comment by analogue** [comment]
See #16

**Comment by jnb** [comment]
:+1:

**Pull request merged**
